### ISSUE TITLE
Add note about TLS deprecations

### ISSUE THREAD

**Issue by weaverryan** [knpuniversity/stripe#3]
At around 3:56 (so, after we submit the form) of http://knpuniversity.com/screencast/stripe/charge-it, let's add the following note:

> If you get some sort of API or connection, you may need to upgrade some TLS security settings: https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#php

**Comment by bocharsky-bw** [comment]
I suppose this one for Leanna to upgrade the video too?

P.S. Note is added to the script content in 4ba01ce .

**Comment by Leannapelham** [comment]
Done!
