### ISSUE TITLE
Building custom checkout form is outdated

### ISSUE THREAD

**Issue by MolloKhan** [knpuniversity/stripe#4]
I started watching this tutorial (which is great and fun :D) and I found that stripe docs has changed a bit, there is a new way to create your own custom forms by using **Elements**, it might be cool if we add a note or something mentioning this, because **stripe's docs site** changed it's desing, and it could be confusing for our users

**Comment by bocharsky-bw** [comment]
Good discovery! Let's add a note, could you add it in place where it will be more appropriate (I suppose it should be on a page where we create custom forms)?

P.S. it was very unexpected when they changed their docs design right after our tutorial was released :/

**Comment by weaverryan** [comment]
Thanks guys! I've just created an issue internally to track this (just to keep things organize in one spot!)
